### ISSUE TITLE
Unescaped character literals `?(', `?)'

### ISSUE THREAD

**Issue by manuel-uberti** [politza/tablist#10]
Hi,

with latest `tablist` from MELPA (installed as a dependency of `pdf-tools`), I get this message in `*Messages*`:
```
Loading ‘tablist-filter’: unescaped character literals `?(', `?)' detected!
```
I don't see a backtrace if I enable `debug-on-error`, so I can't give you more details on that message.

This is some info about my environment, in case you need it:
```
GNU Emacs 27.0.50 (build 17, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2019-01-29

Repository revision: 137b65a9b0a4118adda50f34375b4960701542e9
Configured using:
--host=x86_64-debian-linux-gnu --with-modules

Emacs uptime: 3 minutes, 42 seconds
Default font: Source Code Pro
Colour theme: sanityinc-tomorrow-night
Operating system: Ubuntu 18.04.1 LTS
Window system: x11
Desktop environment: GNOME Shell 3.28.3
```

**Comment by politza** [comment]
This is just a warning.

There is a more severe incompatible change with Emacs 27 regarding
window--display-buffer (in both packages) which I've also just fixed.

**Comment by manuel-uberti** [comment]
Thanks for the fix, the message is gone now.
