### ISSUE TITLE
Bug: mode-line-misc-info elements are not always lists

### ISSUE THREAD

**Issue by jaor** [politza/tablist#13]
Here: https://github.com/politza/tablist/blob/master/tablist.el#L312 it is assumed that
all elements in `mode-line-misc-info` are lists (due to `:key 'car`), but that doesn't need to be the case: there can be symbols or strings as elements.  When a package adds to `mode-line-misc-info` an entry that is not a list, tablist-init throws an error and cannot be used. Using `:key 'car-safe` instead fixes the problem, i think.

Thanks!

**Comment by politza** [comment]
Can you provide a patch?
