### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by dunn** [politza/tablist#2]
If this repository is or has been in a stable state, it'd be great to get a tagged release for MELPA Stable and [Homebrew](https://github.com/Homebrew/homebrew-emacs)!  :heart_eyes_cat:

**Comment by akermu** [comment]
It would be very nice if you tag it as 0.70 like in the tablist.el, because for pdf-tools is uninstallable from melpa-stable, because it needs tablist 0.70 instead of 0.60. Thanks!

**Comment by politza** [comment]
To git@github.com:politza/tablist
- [new tag]         v0.70 -> v0.70

Is this OK ?

**Comment by dunn** [comment]
Yeah, thanks!!
