### ISSUE TITLE
I reinvented this package :-(

### ISSUE THREAD

**Issue by Silex** [politza/tablist#3]
Hello,

I just found out about this package today.

I wrote https://github.com/Silex/tabulated-list-extensions and today I realised I essentially reinvented this package.

The only thing maybe worth adding to your package is the `tle-auto-resize-column` functions.

So, would you be ok with me making a PR to this package with the thing I thing would be worth it?

Basically, the first thing I'd do is massively improve your README

**Comment by politza** [comment]
Philippe Vaucher notifications@github.com writes:

> The only thing maybe worth adding to your package is the
> tle-auto-resize-column functions.

What does it do ? I suppose fitting the width of a column to it's
content, in which case a better name would be something containing a
phrase like `fit-to-xxx.

> So, would you be ok with me making a PR to this package with the thing
> I thing would be worth it?

As long as you're talking about a couple of simple functions, go ahead.
I feel like this package is already a little bit bloated, though I'm not
sure whether this is a problem or should be strived for ;-) .

> Basically, the first thing I'd do is massively improve your README

That's very welcome.

**Comment by Silex** [comment]
Hehe, it was originally named `tle-fit-column-to-contents` but I thought it was a bad name. Maybe not after all :)

Ok PR incoming when I have some time.

**Comment by politza** [comment]
Philippe Vaucher notifications@github.com writes:

> Hehe, it was originally named tle-fit-column-to-contents [...]

I think, `auto' suggests, that it does something without user
interaction, which is not the case.

**Comment by Silex** [comment]
PR incoming
